export const COMPANY_INFO = {
  name: "Nagarkot Food Product Pvt Ltd",
  brandName: "Ugna Ji",
  directors: ["Sangam Agrawal", "Arun Kumar Agrawal"],
  address: "Kh no 1110, gali no 18, rithala delhi 110085, india",
  email: "sangam@nagarkotfood.in",
  mobile: "+91 831 918 0429",
  whatsapp: "918319180429",
  tagline: "Premium Roasted Flavoured Makhana",
  logo: "https://cdn.jsdelivr.net/gh/Ram-Rajput-Code/ugnaji-website-assets/images/NFPPLlogo.jpeg",
  instagram: "https://www.instagram.com/ugnajiii?utm_source=qr&igsh=MWUyYTY4djJtOHlnOQ==",
};

export const PRODUCTS = [
  {
    id: "black-pepper",
    name: "Black Pepper Makhana",
    flavor: "Black Pepper",
    color: "bg-blue-600",
    textColor: "text-blue-600",
    description: "Light, crunchy and healthy roasted makhana with a spicy kick of black pepper.",
    image: "https://cdn.jsdelivr.net/gh/Ram-Rajput-Code/ugnaji-website-assets/images/UgnaMakhanaBlackPepper.jpeg",
    features: ["Rich in iron", "Calcium", "Antioxidants", "Loaded with Protein"],
  },
  {
    id: "garlic",
    name: "Garlic Makhana",
    flavor: "Garlic",
    color: "bg-green-600",
    textColor: "text-green-600",
    description: "Perfectly roasted makhana infused with the aromatic and savory taste of garlic.",
    image: "https://cdn.jsdelivr.net/gh/Ram-Rajput-Code/ugnaji-website-assets/images/UgnaMakhanaGarlic.jpeg",
    features: ["100% Organic", "Pure and Natural", "Heart Healthy", "Low Calorie"],
  },
  {
    id: "himalayan-salt",
    name: "Himalayan Salt Makhana",
    flavor: "Himalayan Salt",
    color: "bg-purple-600",
    textColor: "text-purple-600",
    description: "Simple yet sophisticated, seasoned with pure Himalayan pink salt for a clean taste.",
    image: "https://cdn.jsdelivr.net/gh/Ram-Rajput-Code/ugnaji-website-assets/images/UgnaMakhanaHimalayanSalt.jpeg",
    features: ["Mineral Rich", "No Artificial Flavors", "Gluten Free", "Vegan Friendly"],
  },
  {
    id: "peri-peri",
    name: "Peri Peri Masala Makhana",
    flavor: "Peri Peri Masala",
    color: "bg-red-600",
    textColor: "text-red-600",
    description: "A fiery blend of spices for those who love a bold and tangy snacking experience.",
    image: "https://cdn.jsdelivr.net/gh/Ram-Rajput-Code/ugnaji-website-assets/images/UgnaMakhanaPeriPeriMasala.jpeg",
    features: ["Spicy & Tangy", "Zero Trans Fat", "High Fiber", "Nutritious Snack"],
  },
  {
    id: "pudina",
    name: "Pudina Makhana",
    flavor: "Pudina",
    color: "bg-emerald-600",
    textColor: "text-emerald-600",
    description: "Refreshing minty flavor combined with the crunch of roasted makhana.",
    image: "https://cdn.jsdelivr.net/gh/Ram-Rajput-Code/ugnaji-website-assets/images/UgnaMakhanaPudina.jpeg",
    features: ["Cooling Effect", "Digestive Benefits", "Natural Herbs", "Light Snack"],
  },
    {
      id: "chatpatekarare",
      name: "Chatpate Karare Puffs",
      flavor: "Chatpate Karare",
      color: "bg-orange-600",
      textColor: "text-orange-600",
      description: "A deliciously tangy and spicy mix of traditional Indian chatpata flavors with a crispy crunch.",
      image: "https://cdn.jsdelivr.net/gh/Ram-Rajput-Code/ugnaji-website-assets@main/UgnaChatpateKarare.jpg",
      features: ["Tangy Taste", "Crispy Texture", "Indian Masala Blend", "Perfect Tea-Time Snack"],
    },
    {
      id: "hotchilli",
      name: "Hot Chilli Puffs",
      flavor: "Hot Chilli",
      color: "bg-rose-600",
      textColor: "text-rose-600",
      description: "Extra spicy roasted puffs for those who love intense heat and bold flavors.",
      image: "https://cdn.jsdelivr.net/gh/Ram-Rajput-Code/ugnaji-website-assets@main/UgnaHotCHilli.jpg",
      features: ["Extra Spicy", "Bold Flavor", "Crunchy Snack", "High Energy"],
    },
    {
      id: "manchurian",
      name: "Manchurian Puffs",
      flavor: "Manchurian",
      color: "bg-indigo-600",
      textColor: "text-indigo-600",
      description: "Fusion of Indo-Chinese Manchurian flavors with crispy roasted puffs for a unique taste.",
      image: "https://cdn.jsdelivr.net/gh/Ram-Rajput-Code/ugnaji-website-assets@main/UgnaManchurian.jpg",
      features: ["Indo-Chinese Flavor", "Savory Taste", "Crunchy Delight", "Unique Snack"],
    },
    {
      id: "pizzapunch",
      name: "Pizza Punch Puffs",
      flavor: "Pizza Punch",
      color: "bg-yellow-600",
      textColor: "text-yellow-600",
      description: "A cheesy and herby pizza-inspired flavor that gives your snack time a fun twist.",
      image: "https://cdn.jsdelivr.net/gh/Ram-Rajput-Code/ugnaji-website-assets@main/UgnaPizzaPunch.jpg",
      features: ["Cheesy Flavor", "Herb Infused", "Kid Friendly", "Fun Snack"],
    },
    {
      id: "tandoorimasala",
      name: "Tandoori Masala Puffs",
      flavor: "Ugna Tandoori Masala",
      color: "bg-amber-700",
      textColor: "text-amber-700",
      description: "Authentic tandoori spices blended with roasted puffs for a smoky and rich taste.",
      image: "https://cdn.jsdelivr.net/gh/Ram-Rajput-Code/ugnaji-website-assets@main/UgnaTandooriMasala.jpg",
      features: ["Smoky Flavor", "Rich Spices", "Protein Rich", "Traditional Taste"],
    },
  ];

export const CERTIFICATIONS = [
  { name: "FSSAI", icon: "ShieldCheck" },
  { name: "ISO 22000", icon: "Award" },
  { name: "HACCP", icon: "CheckCircle" },
  { name: "GMP", icon: "Factory" },
];
